
[tool.mypy]
allow_redefinition = true
disable_error_code = ["var-annotated", "syntax", "has-type", "name-defined"]
python_version="3.10"


[tool.pylint.main]
jobs=1
py-version="3.10"
disable = ["missing-class-docstring", "too-few-public-methods", "line-too-long", "no-else-return", "trailing-newlines", "trailing-whitespace", "too-many-lines", "too-many-arguments", "wildcard-import", "consider-using-from-import", "too-many-locals"]
